### ISSUE TITLE
Tags, Channels & Atomicity

### ISSUE THREAD

**Issue by myhndl** [polyswarm/e2e#14]
**Is your feature request related to a problem? Please describe.**
Currently, when CI passes e2e tests on `master` branches, it pushes all related images to Docker Hub with the tag `:latest`. This is racey. Consider a multi-project breaking change: a consumer of these images may pull some updated and some not-yet-updated images, causing breakage.

**Describe the solution you'd like**
In addition to tagging and pushing `:latest` (so as to not break anything), I propose we develop a notion of `channel`s and `release_id`s and tags occur in the following manner:

```
v<channel>-<release_id>-<metadata>
```

Where:
* `channel` = [`dev`|`stable`]
* `release-id` is an iterator for that particular channel
* `metadata` is usage-defined. Currently this is limited to `withartifacts` for `polyswarm-client`

After pushing these new tags, CI removes images tagged as such:

```
v<channel>-<released_id-1>-<metadata>
```

**Describe alternatives you've considered**
I considered a number of other ways to achieve atomicity, but this design seems like the best idea so far. We want to avoid timestamps because syncing issues.

**Comment by scsich** [comment]
I'm not sure there is an issue here that warrants this much complexity. Consider this:
1. *if e2e passes* all containers should be deemed to not have "multi-project breaking changes" 
2. When pushing *all passing images* you should be pushing to tag $CI_REF_NAME_SLUG+$CI_COMMIT_SHA. Pushing takes time, this is where your race is.
3. Once done pushing retag `polyswarm/*:"$CI_REF_NAME_SLUG-$CI_COMMIT_SHA"` with latest or branch name. If anyone is unlucky enough to hit docker hub in these few seconds... oh well.
4. RM the old tags

Note that we will likely be pushing some private images to private docker hub.

See https://github.com/polyswarm/development-private/issues/35 for CD thoughts.

**Comment by myhndl** [comment]
Per discussion in Slack, we're abandoning this direction; conversation continues in: https://github.com/polyswarm/development-private/issues/35
