### ISSUE TITLE
Restore Log Streaming

### ISSUE THREAD

**Issue by myhndl** [polyswarm/e2e#15]
**Describe the bug**
`e2e.sh` streamed log output from containers under test. Impending merge from `feature/polypoly` (sp) will remove this feature.  This will make it more difficult to diagnose failures.

**To Reproduce**
Kick e2e.

Example: https://gitlab.polyswarm.io/polyswarm/e2e/-/jobs/5000

**Expected behavior**
Log output from container tests are streamed to stdout.

Example: https://gitlab.polyswarm.io/polyswarm/e2e/-/jobs/4978

**Comment by scsich** [comment]
Done in a thread now in 
037d03566f0cae9b3e413d521f816f1938867385
