### ISSUE TITLE
Auto-Deploy (CD) to Staging is Unreliable

### ISSUE THREAD

**Issue by myhndl** [polyswarm/e2e#18]
**Describe the bug**
It appears as though auto-deploy of passing master branches (CD) did not complete last week, resulting in stagnant code on Staging and resurfacing of an already-fixed bug.

**To Reproduce**
Run an e2e pipeline

**Comment by myhndl** [comment]
At least part of the problem is this: https://github.com/polyswarm/poly-mon/issues/2

**Comment by scsich** [comment]
Might be addressed by https://github.com/polyswarm/poly-mon/commit/cd8718871d0f9c9fbabc936efdb1aef5eb76ab79 

Let's see...

**Comment by myhndl** [comment]
Appears to be addressed; `polyswarmd` changes were auto-deployed. Closing for now.
