### ISSUE TITLE
Dump logs for all failing containers

### ISSUE THREAD

**Issue by Rizato** [polyswarm/e2e#28]
**Is your feature request related to a problem? Please describe.**
The exception thrown in `check_test_container` causes e2e to exit after one failure, potentially hiding multiple causes of failure

**Describe the solution you'd like**
Catch the exceptions, marking a failure, but continue to check.
This will require mods to the relay dump I just added. 

**Additional context**
#27

**Comment by myhndl** [comment]
@mjkoo did you recent changes to e2e cover this?
