### ISSUE TITLE
Auto-Push Release Branches / Tags to Docker Hub

### ISSUE THREAD

**Issue by myhndl** [polyswarm/e2e#3]
Release tags will be of the form `v*`.

These tags need to be **protected** in all repos that go into e2e.

Any push to a `v*` tag does:
* e2e testing of all other repos with the identical `v*` tag
* if any other repo doesn't have an identical tag, fail e2e testing, DO NOT fall back to `master`

**Comment by ceseale** [comment]
Done, example [here](https://gitlab.polyswarm.io/externalci/ambassador/pipelines/2806)
