### ISSUE TITLE
Speedup: --cache-from

### ISSUE THREAD

**Issue by myhndl** [polyswarm/e2e#7]
Explore using `--cache-from` for speeding up Docker image builds: https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84

This would necessitate changes in all repos that are e2e-enabled.

**Comment by ceseale** [comment]
run time reduced from sometimes 17 minutes to about 8!
https://gitlab.polyswarm.io/polyswarm/e2e/-/jobs/4214
