### ISSUE TITLE
Speedup: overlay2 as Storage Driver

### ISSUE THREAD

**Issue by myhndl** [polyswarm/e2e#8]
https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84

This would necessitate change in all e2e-enabled repos.

**Comment by ceseale** [comment]
run time reduced from sometimes 17 minutes to about 8!
https://gitlab.polyswarm.io/polyswarm/e2e/-/jobs/4214
